import { useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useChat } from '../context/ChatContext';
import api from '../services/api';
import Button from '../components/Button';
import { Setup } from './Profile';

export default function Auth() {
  const { profile, saveProfile, setUser } = useChat(); const navigate = useNavigate(); const { pathname } = useLocation();
  const registerMode = pathname.endsWith('register'); const rememberedUsername = document.cookie.match(/(?:^|; )sparklink_username=([^;]*)/)?.[1]; const [username, setUsername] = useState(rememberedUsername ? decodeURIComponent(rememberedUsername) : ''); const [password, setPassword] = useState(''); const [rememberMe, setRememberMe] = useState(Boolean(rememberedUsername)); const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const endpoint = registerMode ? '/auth/register' : '/auth/login'; const payload = registerMode ? { ...profile, username, password, rememberMe } : { username, password, rememberMe }; const { data } = await api.post(endpoint, payload); if (rememberMe) document.cookie = `sparklink_username=${encodeURIComponent(username)}; Max-Age=${30 * 24 * 60 * 60}; Path=/; SameSite=Lax`; else document.cookie = 'sparklink_username=; Max-Age=0; Path=/; SameSite=Lax'; setUser(data.user); saveProfile({ name: data.user.name, gender: data.user.gender, dateOfBirth: new Date(data.user.dateOfBirth).toISOString().slice(0, 10) }); navigate('/'); } catch (e) { setError(e.response?.data?.message || 'Unable to sign in. Please try again.'); } finally { setBusy(false); } };
  if (registerMode && (!profile.name || !profile.gender || !profile.dateOfBirth)) return <Setup title="Set up your profile first" step="1 / 3"><p>We need your basic profile details before creating an account.</p><Button onClick={() => navigate('/profile')}>Set up profile</Button></Setup>;
  return <Setup title={registerMode ? 'Join the chai circle' : 'Welcome back'} step="✓"><p>{registerMode ? 'Create your account to save your profile for future chai talks.' : 'Sign in to pick up your next chai talk.'}</p><form onSubmit={submit}><input className="form-input" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="Username" autoComplete="username" required /><div className="password-input"><input className="form-input" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password (8+ characters)" type={showPassword ? 'text' : 'password'} autoComplete={registerMode ? 'new-password' : 'current-password'} required minLength="8" /><button type="button" onClick={() => setShowPassword(!showPassword)} aria-label={showPassword ? 'Hide password' : 'Show password'}>{showPassword ? 'Hide' : 'Show'}</button></div><label className="remember-check"><input type="checkbox" checked={rememberMe} onChange={(e) => setRememberMe(e.target.checked)} /> <span>Remember me for 30 days</span></label><p className="error">{error}</p><Button disabled={busy} type="submit">{busy ? 'Please wait…' : registerMode ? 'Join CHAIYO' : 'Sign in'}</Button></form><p className="auth-switch">{registerMode ? 'Already have an account?' : 'New to CHAIYO?'} <Link to={registerMode ? '/auth/login' : '/profile'}>{registerMode ? 'Sign in' : 'Create an account'}</Link></p></Setup>;
}
