import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const messages = {
  en: {
    languagePrompt: 'Choose your language', languageHelp: 'You can change this later from the home page.', english: 'English', hindi: 'हिंदी',
    ourSpace: 'Our space', howItWorks: 'How it works', signOut: 'Sign out', signIn: 'Sign in', meetSomeone: 'Meet someone', findCompany: 'Find company', welcome: 'Namaste, {name}',
    eyebrow: 'GARAM CHAI • REAL TALKS • 18+', heroTitle: 'Pour your heart out over', chai: 'chai.', heroText: 'CHAIYO is a warm little corner for honest conversations with someone new. Share a thought, a laugh, or what’s been on your heart.',
    textChat: 'Text chat', textHint: 'Message one-to-one', audioCall: 'Audio call', audioHint: 'Talk voice-to-voice', videoCall: 'Video call', videoHint: 'Meet face-to-face', safety: 'Be kind, keep it consensual, and confirm that you’re 18 or older.', warm: 'A little warmth, one chat away',
    chooseConnection: 'Choose your connection', chooseConnectionText: 'Pick text, audio, or video for your chai talk.', findChai: 'Find chai company', findChaiText: 'We’ll pair you with someone in the same mode.', speakHeart: 'Speak from the heart', speakHeartText: 'Talk, listen, or move on whenever you want.',
    aboutYou: 'A little about you', identityHelp: 'Choose how you identify. This helps us build a better match experience.', continue: 'Continue', male: 'Male', female: 'Female',
    born: 'When were you born?', bornHelp: 'We use this only to confirm you’re eligible to talk here.', ageError: 'You must be 18 or older to use CHAIYO.', nameTitle: 'What should we call you?', nameHelp: 'Your first name is visible only while you are chatting.', namePlaceholder: 'Your first name', nameError: 'Please use a name between 2 and 50 characters.', review: 'Review profile',
    ready: 'Ready for a chai talk?', readyHelp: 'Choose how you’d like to connect. You’ll only be matched with someone choosing the same mode.', name: 'Name', identity: 'Identity', createAccount: 'Create account to continue →', findMode: 'Find {mode} company →', goBack: 'Go back',
    welcomeBack: 'Welcome back', joinCircle: 'Join the chai circle', loginHelp: 'Sign in to pick up your next chai talk.', registerHelp: 'Create your account to save your profile for future chai talks.', username: 'Username', password: 'Password (8+ characters)', remember: 'Remember me for 30 days', wait: 'Please wait…', join: 'Join CHAIYO', newHere: 'New to CHAIYO?', alreadyAccount: 'Already have an account?', createAnAccount: 'Create an account', setupFirst: 'Set up your profile first', setupFirstHelp: 'We need your basic profile details before creating an account.', setupProfile: 'Set up profile', unableSignIn: 'Unable to sign in. Please try again.', show: 'Show', hide: 'Hide',
    permission: 'Permission needed', permissionDevice: 'Microphone and camera access is required for calls. Please allow it in your browser.', unsupportedDevice: 'Your browser does not support microphone and camera access.', tryAgain: 'Try again', returnHome: 'Return home', searching: 'Finding a {mode} chai talk…', searchingHelp: 'Looking for someone who chose {mode} chat too.', leaveQueue: 'Leave the chai queue',
    chatEnded: 'Chat ended', chaiText: 'Chai text chat', leaveChat: 'Leave chat', returnHomeChat: 'Return home', chatLasted: 'This chat lasted {duration}.', matched: 'You matched with', startGently: 'Start gently.', findAnother: 'Find another chai talk →', shareMind: 'Share what’s on your mind…', send: 'Send', chaiFriend: 'Chai friend',
    connecting: 'Connecting securely…', connected: 'Connected', matchLeft: 'Your match left the call.', connectionFailed: 'Connection failed.', backCamera: 'Back camera is not available on this device.', frontCamera: 'Front camera is not available on this device.', endedCall: 'You ended this call.', unsafe: 'Video blurred: potentially unsafe content was detected.', you: 'You', audioTalk: 'Audio chai talk', connectedTalk: 'You’re connected — let the conversation steep.', talkEnded: 'CHAI TALK ENDED', nextConnect: 'How would you like to connect next?', chattedFor: 'You chatted for {duration}. Choose a mode and we’ll find someone looking for the same kind of conversation.', newTalk: 'Chai talk with someone new', listenShare: 'Listen, share, connect', sayHello: 'Say hello 👋', mute: '◉ Mute', unmute: '◉ Unmute', cameraOn: '▣ Camera on', cameraOff: '▣ Camera off', flip: '↻ Flip', switching: '↻ Switching', next: '↻ Next', end: 'End',
  },
  hi: {
    languagePrompt: 'अपनी भाषा चुनें', languageHelp: 'आप इसे बाद में होम पेज से बदल सकते हैं।', english: 'English', hindi: 'हिंदी',
    ourSpace: 'हमारी जगह', howItWorks: 'यह कैसे काम करता है', signOut: 'साइन आउट', signIn: 'साइन इन', meetSomeone: 'किसी से मिलें', findCompany: 'साथी खोजें', welcome: 'नमस्ते, {name}',
    eyebrow: 'गरम चाय • सच्ची बातें • 18+', heroTitle: 'चाय पर दिल की बातें', chai: 'करें।', heroText: 'CHAIYO नए लोगों के साथ ईमानदार बातचीत का एक गर्मजोशी भरा कोना है। कोई विचार, हँसी या अपने मन की बात साझा करें।',
    textChat: 'टेक्स्ट चैट', textHint: 'आमने-सामने संदेश', audioCall: 'ऑडियो कॉल', audioHint: 'आवाज़ में बात करें', videoCall: 'वीडियो कॉल', videoHint: 'आमने-सामने मिलें', safety: 'दयालु रहें, सहमति का ध्यान रखें और पुष्टि करें कि आपकी आयु 18 वर्ष या अधिक है।', warm: 'बस एक चैट की दूरी पर थोड़ी गर्माहट',
    chooseConnection: 'अपना तरीका चुनें', chooseConnectionText: 'अपनी चाय वाली बातचीत के लिए टेक्स्ट, ऑडियो या वीडियो चुनें।', findChai: 'चाय का साथी खोजें', findChaiText: 'हम आपको उसी मोड वाले किसी व्यक्ति से मिलाएँगे।', speakHeart: 'दिल से बात करें', speakHeartText: 'बात करें, सुनें या जब चाहें आगे बढ़ें।',
    aboutYou: 'आपके बारे में थोड़ा', identityHelp: 'आप अपनी पहचान कैसे करते हैं, चुनें। इससे बेहतर मैच ढूँढने में मदद मिलती है।', continue: 'आगे बढ़ें', male: 'पुरुष', female: 'महिला',
    born: 'आपका जन्म कब हुआ?', bornHelp: 'हम इसका उपयोग केवल यह पुष्टि करने के लिए करते हैं कि आप यहाँ बात करने के योग्य हैं।', ageError: 'CHAIYO इस्तेमाल करने के लिए आपकी आयु 18 वर्ष या अधिक होनी चाहिए।', nameTitle: 'हम आपको क्या कहें?', nameHelp: 'आपका पहला नाम केवल चैट के दौरान दिखाई देगा।', namePlaceholder: 'आपका पहला नाम', nameError: 'कृपया 2 से 50 अक्षरों का नाम लिखें।', review: 'प्रोफ़ाइल देखें',
    ready: 'चाय पर बात करने के लिए तैयार हैं?', readyHelp: 'जुड़ने का तरीका चुनें। आपका मैच केवल उसी मोड वाले व्यक्ति से होगा।', name: 'नाम', identity: 'पहचान', createAccount: 'आगे बढ़ने के लिए खाता बनाएँ →', findMode: '{mode} साथी खोजें →', goBack: 'वापस जाएँ',
    welcomeBack: 'वापसी पर स्वागत है', joinCircle: 'चाय मंडली से जुड़ें', loginHelp: 'अपनी अगली चाय वाली बातचीत जारी रखने के लिए साइन इन करें।', registerHelp: 'भविष्य की चाय बातचीत के लिए अपनी प्रोफ़ाइल सहेजने हेतु खाता बनाएँ।', username: 'यूज़रनेम', password: 'पासवर्ड (8+ अक्षर)', remember: 'मुझे 30 दिनों तक याद रखें', wait: 'कृपया प्रतीक्षा करें…', join: 'CHAIYO से जुड़ें', newHere: 'CHAIYO पर नए हैं?', alreadyAccount: 'क्या आपका खाता है?', createAnAccount: 'खाता बनाएँ', setupFirst: 'पहले अपनी प्रोफ़ाइल बनाएँ', setupFirstHelp: 'खाता बनाने से पहले हमें आपकी बुनियादी प्रोफ़ाइल जानकारी चाहिए।', setupProfile: 'प्रोफ़ाइल बनाएँ', unableSignIn: 'साइन इन नहीं हो सका। कृपया फिर कोशिश करें।', show: 'दिखाएँ', hide: 'छिपाएँ',
    permission: 'अनुमति चाहिए', permissionDevice: 'कॉल के लिए माइक्रोफ़ोन और कैमरे की अनुमति चाहिए। कृपया ब्राउज़र में अनुमति दें।', unsupportedDevice: 'आपका ब्राउज़र माइक्रोफ़ोन और कैमरे का समर्थन नहीं करता।', tryAgain: 'फिर कोशिश करें', returnHome: 'होम पर लौटें', searching: '{mode} चाय बातचीत खोजी जा रही है…', searchingHelp: 'आपके चुने हुए {mode} मोड वाले व्यक्ति को खोज रहे हैं।', leaveQueue: 'चाय कतार छोड़ें',
    chatEnded: 'चैट समाप्त हुई', chaiText: 'चाय टेक्स्ट चैट', leaveChat: 'चैट छोड़ें', returnHomeChat: 'होम पर लौटें', chatLasted: 'यह चैट {duration} चली।', matched: 'आपका मैच हुआ है', startGently: 'धीरे से शुरुआत करें।', findAnother: 'एक और चाय बातचीत खोजें →', shareMind: 'मन की बात साझा करें…', send: 'भेजें', chaiFriend: 'चाय दोस्त',
    connecting: 'सुरक्षित रूप से जुड़ रहे हैं…', connected: 'जुड़ गए', matchLeft: 'आपका मैच कॉल छोड़ गया।', connectionFailed: 'कनेक्शन विफल हुआ।', backCamera: 'इस डिवाइस पर पिछला कैमरा उपलब्ध नहीं है।', frontCamera: 'इस डिवाइस पर सामने का कैमरा उपलब्ध नहीं है।', endedCall: 'आपने यह कॉल समाप्त कर दी।', unsafe: 'वीडियो धुंधला किया गया: संभावित रूप से असुरक्षित सामग्री मिली।', you: 'आप', audioTalk: 'ऑडियो चाय बातचीत', connectedTalk: 'आप जुड़ गए हैं — बातचीत को धीरे-धीरे आगे बढ़ने दें।', talkEnded: 'चाय बातचीत समाप्त', nextConnect: 'अब आप कैसे जुड़ना चाहेंगे?', chattedFor: 'आपने {duration} बात की। मोड चुनें और हम उसी तरह की बातचीत चाहने वाले व्यक्ति को खोजेंगे।', newTalk: 'किसी नए के साथ चाय पर बात', listenShare: 'सुनें, साझा करें, जुड़ें', sayHello: 'नमस्ते कहें 👋', mute: '◉ म्यूट', unmute: '◉ आवाज़ चालू', cameraOn: '▣ कैमरा चालू', cameraOff: '▣ कैमरा बंद', flip: '↻ कैमरा बदलें', switching: '↻ बदल रहे हैं', next: '↻ अगला', end: 'समाप्त',
  },
};

const LanguageContext = createContext();
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('chaiyo-language'));
  const chooseLanguage = (nextLanguage) => { localStorage.setItem('chaiyo-language', nextLanguage); setLanguage(nextLanguage); };
  useEffect(() => { document.documentElement.lang = language || 'en'; }, [language]);
  const value = useMemo(() => ({ language, chooseLanguage, t: (key, values = {}) => (messages[language || 'en'][key] || key).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? '') }), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export const useLanguage = () => useContext(LanguageContext);
